[package]
name = "hands-on-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5.0", default-features = false, features = [
    "bevy_winit",
    "bevy_wgpu",
    "render",
    "png",
] }
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap.git/", rev = "93969ae426fdaa32be70625e6f725ad1cd7eddb1" }
fastrand = "1.5.0"
ntest = "0.7.3"
anyhow = "1.0.43"
bevy_egui = "0.7.0"
puffin = "0.8.1"
puffin_egui = "0.7.0"
puffin_egui = "0.5.0"
